//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorontoPartyAdvisor.Commands
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.PositionPlaces = new HashSet<PositionPlace>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int RadiusMeters { get; set; }
        public string Address { get; set; }
        public string StreetName { get; set; }
        public int Number { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
        public System.DateTimeOffset DateUpdated { get; set; }
        public string ImagePath { get; set; }
        public bool Published { get; set; }
        public string FacebookId { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<PositionPlace> PositionPlaces { get; set; }
    }
}
