//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorontoPartyAdvisor.Commands
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.PositionPlaces = new HashSet<PositionPlace>();
        }
    
        public int Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int UserId { get; set; }
        public System.DateTimeOffset Date { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<PositionPlace> PositionPlaces { get; set; }
    }
}
