//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorontoPartyAdvisor.Commands
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Positions = new HashSet<Position>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string FacebookToken { get; set; }
        public string Email { get; set; }
        public string FacebookId { get; set; }
        public int Timezone { get; set; }
        public string Locale { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
        public System.DateTimeOffset LastLoginDate { get; set; }
        public int Points { get; set; }
    
        public virtual ICollection<Position> Positions { get; set; }
    }
}
